export const SOURCE_CATALOG = [
  { id: "osnap", name: "OSNAP", family: "overturning", tier: "direct", cadence: "research release", latency: "multi-year public release", revision: "versioned research product", adapter: "planned", url: "https://www.o-snap.org/" },
  { id: "rapid", name: "RAPID", family: "overturning", tier: "direct", cadence: "research release", latency: "months to years", revision: "versioned research product", adapter: "planned", url: "https://rapid.ac.uk/data/data-download" },
  { id: "argo", name: "Argo", family: "density", tier: "observed", cadence: "near real time", latency: "12–24 hours", revision: "real-time then delayed-mode QC", adapter: "manifest-ready", url: "https://argo.ucsd.edu/data/data-from-gdacs/" },
  { id: "en4", name: "EN4", family: "density", tier: "observed", cadence: "monthly", latency: "1–2 months", revision: "versioned analysis", adapter: "manifest-ready", accessNote: "Non-commercial licence review required", url: "https://www.metoffice.gov.uk/hadobs/en4/" },
  { id: "copernicus-phy", name: "Copernicus", family: "convection", tier: "reanalysis", cadence: "product-specific", latency: "product-specific", revision: "analysis and reanalysis streams", adapter: "planned", url: "https://data.marine.copernicus.eu/products" },
  { id: "era5", name: "ERA5", family: "freshwater", tier: "reanalysis", cadence: "daily and monthly", latency: "~5 days preliminary; 2–3 months final", revision: "ERA5T then final ERA5", adapter: "request-ready", accessNote: "CDS_API_KEY required for ingestion worker", url: "https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels" },
  { id: "nsidc-sic", name: "NSIDC", family: "freshwater", tier: "observed", cadence: "daily", latency: "~1 day preliminary", revision: "near-real-time then final", adapter: "planned", url: "https://nsidc.org/data/g10016" },
  { id: "grace-fo", name: "GRACE-FO", family: "freshwater", tier: "observed", cadence: "monthly", latency: "variable", revision: "versioned monthly solution", adapter: "planned", url: "https://grace.jpl.nasa.gov/data/get-data/" },
  { id: "oisst", name: "OISST", family: "thermalPattern", tier: "observed", cadence: "daily", latency: "~1 day preliminary", revision: "preliminary then final", adapter: "fetch-ready", url: "https://www.ncei.noaa.gov/products/optimum-interpolation-sst" },
];
